name: Convert Jupyter Notebook to PDF

on:
  push:
    branches:
      - main  # 
  pull_request:

jobs:
  convert-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install nbconvert 
      - name: Convert Notebook to PDF
        run: |
          jupyter nbconvert --to pdf notebook.ipynb

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-notebook
          path: notebook.pdf
