name: Convert Jupyter Notebook to PDF

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  convert-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-extra pandoc

      - name: Install Python Dependencies
        run: |
          pip install nbconvert notebook

      - name: Convert Notebook to PDF
        run: |
          jupyter nbconvert --to pdf --execute notebook.ipynb

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-notebook
          path: notebook.pdf
          compression-level: 0
